# Generated by Django 2.1 on 2018-09-12 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cat_asentamiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cla_asentamiento', models.IntegerField(verbose_name='Clave Asentamiento')),
                ('nom_asentamiento', models.CharField(max_length=200, verbose_name='Nombre Colonia')),
            ],
        ),
        migrations.CreateModel(
            name='cat_codigo_postal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cla_codigo_postal', models.CharField(max_length=20, verbose_name='Codigo Postal')),
            ],
        ),
        migrations.CreateModel(
            name='cat_estado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cla_estado', models.IntegerField(verbose_name='Clave Estado')),
                ('nom_estado', models.CharField(max_length=200, verbose_name='Nombre Estado')),
            ],
        ),
        migrations.CreateModel(
            name='cat_municipio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cla_municipio', models.IntegerField(verbose_name='Clave Municipio')),
                ('nom_municipio', models.CharField(max_length=200, verbose_name='Nombre Municipio')),
                ('cla_estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='colonias.cat_estado')),
            ],
        ),
        migrations.CreateModel(
            name='cat_pais',
            fields=[
                ('cla_pais', models.IntegerField(primary_key=True, serialize=False, verbose_name='Clave Pais')),
                ('nom_pais', models.CharField(max_length=200, verbose_name='Nombre Pais')),
            ],
        ),
        migrations.CreateModel(
            name='cat_tipo_asentamiento',
            fields=[
                ('cla_tipo_asentamiento', models.IntegerField(primary_key=True, serialize=False, verbose_name='Clave Tipo Asentamiento')),
                ('nom_tipo_asentimiento', models.CharField(max_length=200, verbose_name='Nombre Tipo Asentamiento')),
            ],
        ),
        migrations.AddField(
            model_name='cat_municipio',
            name='cla_pais',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='colonias.cat_pais'),
        ),
        migrations.AddField(
            model_name='cat_estado',
            name='cla_pais',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='colonias.cat_pais'),
        ),
        migrations.AddField(
            model_name='cat_codigo_postal',
            name='cla_estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='colonias.cat_estado'),
        ),
        migrations.AddField(
            model_name='cat_codigo_postal',
            name='cla_municipio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='colonias.cat_municipio'),
        ),
        migrations.AddField(
            model_name='cat_codigo_postal',
            name='cla_pais',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='colonias.cat_pais'),
        ),
        migrations.AddField(
            model_name='cat_asentamiento',
            name='cla_codigo_postal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='colonias.cat_codigo_postal'),
        ),
        migrations.AddField(
            model_name='cat_asentamiento',
            name='cla_estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='colonias.cat_estado'),
        ),
        migrations.AddField(
            model_name='cat_asentamiento',
            name='cla_municipio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='colonias.cat_municipio'),
        ),
        migrations.AddField(
            model_name='cat_asentamiento',
            name='cla_pais',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='colonias.cat_pais'),
        ),
        migrations.AddField(
            model_name='cat_asentamiento',
            name='cla_tipo_asentamiento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='colonias.cat_tipo_asentamiento'),
        ),
        migrations.AlterUniqueTogether(
            name='cat_municipio',
            unique_together={('cla_pais', 'cla_estado', 'cla_municipio')},
        ),
        migrations.AlterUniqueTogether(
            name='cat_estado',
            unique_together={('cla_pais', 'cla_estado')},
        ),
        migrations.AlterUniqueTogether(
            name='cat_codigo_postal',
            unique_together={('cla_codigo_postal', 'cla_pais', 'cla_estado', 'cla_municipio')},
        ),
        migrations.AlterUniqueTogether(
            name='cat_asentamiento',
            unique_together={('cla_codigo_postal', 'cla_pais', 'cla_estado', 'cla_municipio', 'cla_asentamiento')},
        ),
    ]
