# Generated by Django 2.1 on 2018-09-10 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CodigoPostal',
            fields=[
                ('cla_codigo_postal', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Codigo Postal')),
            ],
        ),
        migrations.CreateModel(
            name='Colonia',
            fields=[
                ('cla_colonia', models.IntegerField(primary_key=True, serialize=False, verbose_name='Clave Colonia')),
                ('nom_colonia', models.CharField(max_length=200, verbose_name='Nombre Colonia')),
                ('cla_codigo_postal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='colonias.CodigoPostal')),
            ],
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('cla_estado', models.IntegerField(primary_key=True, serialize=False, verbose_name='Clave Estado')),
                ('nom_estado', models.CharField(max_length=200, verbose_name='Nombre Estado')),
            ],
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('cla_municipio', models.IntegerField(primary_key=True, serialize=False, verbose_name='Clave Municipio')),
                ('nom_municipio', models.CharField(max_length=200, verbose_name='Nombre Municipio')),
                ('cla_estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='colonias.Estado')),
            ],
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('cla_pais', models.IntegerField(primary_key=True, serialize=False, verbose_name='Clave Pais')),
                ('nom_pais', models.CharField(max_length=200, verbose_name='Nombre Pais')),
            ],
        ),
        migrations.AddField(
            model_name='estado',
            name='cla_pais',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='colonias.Pais'),
        ),
        migrations.AddField(
            model_name='colonia',
            name='cla_municipio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='colonias.Municipio'),
        ),
        migrations.AddField(
            model_name='codigopostal',
            name='cla_colonia',
            field=models.ManyToManyField(to='colonias.Colonia'),
        ),
        migrations.AddField(
            model_name='codigopostal',
            name='cla_estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='colonias.Estado'),
        ),
        migrations.AddField(
            model_name='codigopostal',
            name='cla_municipio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='colonias.Municipio'),
        ),
        migrations.AddField(
            model_name='codigopostal',
            name='cla_pais',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='colonias.Pais'),
        ),
    ]
