# Generated by Django 2.1 on 2018-10-01 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colonias', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cat_asentamiento',
            name='activo',
            field=models.BooleanField(default=False, verbose_name='Colonia activa'),
        ),
    ]
