# Generated by Django 2.1 on 2018-09-12 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colonias', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cat_codigo_postal',
            name='id',
        ),
        migrations.AlterField(
            model_name='cat_codigo_postal',
            name='cla_codigo_postal',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Codigo Postal'),
        ),
    ]
