# Generated by Django 2.1 on 2018-09-15 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colonias', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat_usuario',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Correo electrónico'),
        ),
        migrations.AlterField(
            model_name='cat_usuario',
            name='es_admin',
            field=models.BooleanField(default=False, verbose_name='Administrador'),
        ),
        migrations.AlterField(
            model_name='cat_usuario',
            name='es_guardia',
            field=models.BooleanField(default=False, verbose_name='Guardia'),
        ),
        migrations.AlterField(
            model_name='cat_usuario',
            name='nom_usuario',
            field=models.CharField(max_length=200, verbose_name='Nombre(s)'),
        ),
    ]
