# Generated by Django 2.1 on 2018-09-28 04:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('colonias', '0002_auto_20180928_0430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat_direccion_usuario',
            name='cla_asentamiento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='colonias.cat_asentamiento'),
        ),
        migrations.AlterField(
            model_name='cat_direccion_usuario',
            name='cla_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
