# Generated by Django 2.1 on 2018-10-01 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('colonias', '0002_cat_asentamiento_activo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cat_codigo_postal',
            options={'verbose_name': 'Código Postal', 'verbose_name_plural': 'Códigos Postales'},
        ),
    ]
