# Generated by Django 2.1 on 2018-09-15 04:05

import colonias.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('colonias', '0002_auto_20180915_0253'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='cat_usuario',
            managers=[
                ('objects', colonias.models.cat_usuario_manager()),
            ],
        ),
        migrations.RemoveField(
            model_name='cat_usuario',
            name='username',
        ),
    ]
