# Generated by Django 2.1 on 2018-10-01 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('colonias', '0003_auto_20181001_1437'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cat_asentamiento',
            options={'verbose_name': 'Asentamiento', 'verbose_name_plural': 'Asentamientos'},
        ),
        migrations.AlterModelOptions(
            name='cat_estado',
            options={'verbose_name': 'Estado', 'verbose_name_plural': 'Estados'},
        ),
        migrations.AlterModelOptions(
            name='cat_municipio',
            options={'verbose_name': 'Municipio', 'verbose_name_plural': 'Municipios'},
        ),
        migrations.AlterModelOptions(
            name='cat_pais',
            options={'verbose_name': 'País', 'verbose_name_plural': 'Paises'},
        ),
        migrations.AlterModelOptions(
            name='cat_usuario',
            options={'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
    ]
