# Generated by Django 2.1 on 2018-09-15 05:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colonias', '0003_auto_20180915_0405'),
    ]

    operations = [
        migrations.CreateModel(
            name='cat_direccion_usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cla_asentamiento', models.IntegerField(verbose_name='Clave Asentamiento')),
                ('nom_calle', models.CharField(max_length=200, verbose_name='Calle')),
                ('numero_ext', models.IntegerField(verbose_name='Numero Exterior')),
                ('numero_int', models.CharField(max_length=200, verbose_name='Interior')),
                ('cla_usuario', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Clave Usuario')),
            ],
        ),
        migrations.AddField(
            model_name='cat_usuario',
            name='cla_asentamiento',
            field=models.ManyToManyField(to='colonias.cat_direccion_usuario', verbose_name='Colonias a las que pertenece'),
        ),
    ]
