# Generated by Django 2.1 on 2018-09-15 05:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('colonias', '0004_auto_20180915_0538'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cat_direccion_usuario',
            name='cla_usuario',
        ),
        migrations.AddField(
            model_name='cat_direccion_usuario',
            name='cla_usuario',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Clave Usuario'),
            preserve_default=False,
        ),
    ]
