# Generated by Django 2.1 on 2018-10-01 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('colonias', '0004_auto_20181001_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat_asentamiento',
            name='cla_codigo_postal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='colonias.cat_codigo_postal', verbose_name='Código Postal'),
        ),
    ]
