# Generated by Django 2.1 on 2018-10-01 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colonias', '0005_auto_20181001_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='cat_usuario',
            name='activo',
            field=models.BooleanField(default=False, verbose_name='Usuario activo'),
        ),
    ]
