# Generated by Django 2.1 on 2018-09-15 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colonias', '0005_auto_20180915_0547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat_direccion_usuario',
            name='numero_int',
            field=models.CharField(max_length=200, null=True, verbose_name='Interior'),
        ),
    ]
