# Generated by Django 2.1 on 2018-10-01 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('colonias', '0006_cat_usuario_activo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cat_usuario',
            name='activo',
        ),
    ]
