# Generated by Django 2.1 on 2018-09-15 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colonias', '0006_auto_20180915_0554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat_direccion_usuario',
            name='numero_int',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Interior'),
            preserve_default=False,
        ),
    ]
