# Generated by Django 2.1 on 2018-09-15 17:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('colonias', '0007_auto_20180915_0558'),
    ]

    operations = [
        migrations.CreateModel(
            name='perfil_guardia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('cla_asentamiento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='colonias.cat_asentamiento')),
                ('cla_usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
