# Generated by Django 2.1 on 2018-09-27 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colonias', '0009_perfil_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat_usuario',
            name='apellido_materno',
            field=models.CharField(max_length=200, null=True, verbose_name='Apellido Materno'),
        ),
    ]
