# Generated by Django 2.1 on 2018-10-02 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colonias', '0009_perfil_vecino'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil_vecino',
            name='nom_calle',
            field=models.CharField(default='', max_length=200, verbose_name='Calle'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='perfil_vecino',
            name='num_exterior',
            field=models.IntegerField(default=0, verbose_name='Numero Exterior'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='perfil_vecino',
            name='num_interior',
            field=models.CharField(blank=True, max_length=200, verbose_name='Interior'),
        ),
    ]
