# Generated by Django 2.1 on 2018-09-27 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('colonias', '0010_auto_20180927_0356'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cat_tipo_asentamiento',
            old_name='nom_tipo_asentimiento',
            new_name='nom_tipo_asentamiento',
        ),
    ]
