# Generated by Django 2.1 on 2018-10-02 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('colonias', '0011_auto_20181002_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil_vecino',
            name='cla_codigo_postal',
            field=models.ForeignKey(default=64800, on_delete=django.db.models.deletion.CASCADE, to='colonias.cat_codigo_postal', verbose_name='Código Postal'),
            preserve_default=False,
        ),
    ]
