# Generated by Django 2.1 on 2018-10-02 17:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('colonias', '0012_perfil_vecino_cla_codigo_postal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil_vecino',
            name='cla_asentamiento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='colonias.cat_asentamiento'),
        ),
        migrations.AlterField(
            model_name='perfil_vecino',
            name='cla_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
