# Generated by Django 2.1 on 2018-10-02 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colonias', '0013_auto_20181002_1706'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cat_usuario',
            name='es_admin',
        ),
        migrations.RemoveField(
            model_name='cat_usuario',
            name='es_guardia',
        ),
        migrations.AddField(
            model_name='perfil_vecino',
            name='es_admin',
            field=models.BooleanField(default=False, verbose_name='Administrador'),
        ),
        migrations.AddField(
            model_name='perfil_vecino',
            name='es_guardia',
            field=models.BooleanField(default=False, verbose_name='Guardia'),
        ),
    ]
