# Generated by Django 2.1 on 2018-10-04 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colonias', '0014_auto_20181002_1947'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='perfil_vecino',
            options={'verbose_name': 'Dirección', 'verbose_name_plural': 'Direcciones'},
        ),
        migrations.AlterField(
            model_name='perfil_vecino',
            name='es_admin',
            field=models.BooleanField(default=False, verbose_name='Admin'),
        ),
    ]
